export const Inputs = [
  {
    name: "name",
    Fieldtype: "Input",
    type: "text",
    label: { ar: "الإسم بالكامل", en: "Name" },
    labelClassName: "login_label",
    placeholder: { ar: "محمود أحمد", en: "Mahmoud Ahmed" },
    col: "12",
  },
  {
    name: "phone",
    Fieldtype: "Input",
    type: "number",
    label: { ar: "رقم الجوال", en: "Phone Number" },
    labelClassName: "login_label",
    placeholder: { ar: "+966 123456789", en: "+966 123456789" },
    col: "12",
  },
  {
    name: "email",
    Fieldtype: "Input",
    type: "email",
    label: { ar: "البريد الإلكترونى", en: "Email" },
    labelClassName: "login_label",
    placeholder: { ar: "username@mail.com", en: "username@mail.com" },
    col: "12",
  },

  {
    name: "password",
    Fieldtype: "Input",
    type: "password",
    label: { ar: "كلمة المرور", en: "Password" },
    labelClassName: "login_label",
    placeholder: { ar: "*********", en: "*********" },
    col: "12",
  },
  {
    name: "Confirmpassword",
    Fieldtype: "Input",
    type: "password",
    label: { ar: " تأكيد كلمة المرور", en: "Confirm Password" },
    labelClassName: "login_label",
    placeholder: { ar: "*********", en: "*********" },
    col: "12",
  },
];
